services:

  file-converter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    environment:
      - PORT=8070
    volumes:
      - fc_tmp:/tmp/fc
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  fc_tmp:
