services:

  file-converter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    environment:
      - PORT=8070
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - fc_data:/app/data
    restart: unless-stopped

volumes:
  fc_data:
